document.addEventListener('DOMContentLoaded', function () {

	var urls = [
	"14aUO0Mf7dWDXW",
	"pOeuPPvO3Lbxu	",
	"26tnjOKyxetqJx196",
	"l3vRiLydJmh7X0Yx2",
	"GIFbrFpayHUwo",
	"l4Jzi0z1TUWsvy0Sc",
	"l3vR4VfkKdHUvv7Us",
	"26FKVMPd6UFZoBuve",
	"lcVSsTpx2s5t6",
	"sKpOy3SV4FcJi",
	"ToMjGpBmDyMmBrMmbf2",
	"TObbUke0z8Mo",
	"xkhn6Ry4taRtC",
	"l3vR4JrVZMzugEMuY",
	"12Y8uwQsnpizCw",
	"detDESm0bahoc",
	"VANjjepUKvXos",
	"3oz8xxRUPIMXsfgUms",
	"l3vR33TV0vszF7rWg",
	"3oz8xGDSz9q3PwRRyU",
	"3oz8xEGM20jA34Ak5W",
	"l3vRbgCJxtSXS9jFe",
	"26ybvMeJmCaPtcNDW",
	"l3vQYcZ7QlnHiUuWY",
	"l3vQXKKENvuCjz5vi",
	"l41Yej9C6OGpcwKSk",
	"bEqrzkLVWC3bW",
	"DD2NmqYhvLiP6",
	"huBkkFR80SqmQ",
	"pDe2oPAuBpzWw",
	"NEfZfV5frVND2",
	"ZeB4HcMpsyDo4",
	"tcAykk8j17GIU",
	"bRJRe4SUFyp2w",
	"xTk9ZRJytbejZGlzqg",
	"uSYQsJQWEv6O4",
	"Wa5JDuv6kzoTC",
	"Xu3FmS0zWUeu4",
	"zndolLCgmIgrS",
	"ysF2pR5F9xC12",
	"OXYZqYu3wnt4I",
	"PLwpHQmiqoeI0",
	"SP6nsoM3MgLFS",
	"mm7kVzakCIz84",
	"MwVhxOu3ZucV2",
	"K43gf9QRjbLeE",
	"LcQEVgl0HMHIY",
	"j4GX2oX1rGRK8",
	"IUkTZ70JRHVdu",
	"IqDx8Fe5CKIx2",
	"fezvdhQOWyoEw",
	"aTHb91YXHGw8g",
	"9rYAlBv4PnP44",
	"a5aoG9lfaKtqM",
	"AZ9E5rrNWsacg",
	"elxoYTTkgpur6",
	"13kcCFShpeVUoo",
	"7vQfoBITd6omc",
	"5M7C95yZ0TQiI",
	"Rt5SYFNtu09IQ",
	"2rJSj83iGYN8c",
	"66wnpo0hMj7HO",
	"MEGcFyjn4D9sI",
	"hMtf0t0g3UP9m",
	"gB5o7HVgpkCYM",
	"nntN4XMNwTzZ6",
	"CEJGxn0ukYPBu",
	"Ex1vQYjPP3fhK",
	"JxbCxr9E7D38c",
	"AVqtlKDqWwAX6",
	"4bxUqi6ATTXTa",
	"lrw5HXVKYozeg",
	"QoCoLo2opwUW4",
	"GrnubHYtJ0ogg",
	"N6funLtVsHW0g",
	"5lwFdRA563PNK",
	"Ai6pliUjWGOu4",
	"jc7wfEtdNuxMs",
	"4Wx3y8GKho2Ri",
	"EEaWn6O9lR2gg",
	"otyk3n3dXb8AM",
	"iyDXvr5Weat20",
	"w6KILRt0tqZ5m",
	"sq1kD9dEzJDEI",
	"qGZQme1rCwj60",
	"gqDbzvWihXOtW",
	"SZWVMQz6gRmdG",
	"FLal1vWiyQIJG",
	"H0Qi5W2KzU5UI",
	"CXTcNfdzbL25G",
	"26xBwFcBGPLNfGbkY",
	"bOKc5QXWlgRAA",
	"YMGFnbPoy1IRy",
	"rviHZFFo433xe",
	"xmFNzRdsaa8dG",
	"qYJJ6sCXD9IFq",
	"qrf1y0LUZ5y8w",
	"6FOWtV5TBMhkQ",
	"r4lsLsqeIpcBy",
	"o8weDZLHeCQaQ",
	"rvmge3zNyfIDm",
	"p8AsqNWMRcLT2",
	"26FKTjNuyE3KGKFxK",
	"l4Jz1Wh9oRPAdas5q",
	"26FKTSd72bgky8Ke4",
	"26FL8IrP4I4KsB8RO",
	"l4JyTpXHZ7Z9crCZq",
	"l0HlFMnvXv4F0uvxm",
	"26FLc6DCJcqYfYcrS",
	"l0HlRhn3b5pCme2Jy",
	"26FLhDEQzSmf1I9Y4",
	"l4Jz5wxjp8MZn9yow",
	"26FLc6DCJcqYfYcrS",
	"mfl23Zigc80iA",
	"VJ8Cx542KlykE",
	"QRN3Awd0mC6ac",
	"l4JyXzZmGC59YLRnO",
	"l4JyJSHgv7qMPJe48",
	"l4JyNtfY71DI0bZzG",
	"d4aUhirySgWNm0og",
	"26ybvMeJmCaPtcNDW",
	"l3vQYcZ7QlnHiUuWY",
	"l41Yy2vHvj4kZs7F6",
	"p8AsqNWMRcLT2",
	"Z89W40XJ3O1dm",
	"ywEsI8CpIjVaE",
	"iMeRr7molZ5XW",
	"4sLyMfds3Z5e0",
	"ECpRBo08Cz7Yk",
	"BAiLboJ1pC45W",
	"NrdIQbvKO4Eww",
	"KudWq0YKBehna",
	"27PVoc4qSMODC",
	"T2MZn1X1XJqBW",
	"Zu3IHLRMxPvX2",
	"3t82HXDa2hlxm",
	"oFnr0c2nbftE4",
	"QEJPkYu5a1qJW",
	"MAlNFmtnvZDJm",
	"7DAniGSCMc86c",
	"DOcUtFr07MGd2",
	"C2egRipVALU9a"
	]

	var pandaUrl = urls[Math.floor(Math.random()*urls.length)];
	console.log('http://api.giphy.com/v1/gifs/' + pandaUrl + '?api_key=dc6zaTOxFJmzC');

	request = new XMLHttpRequest;
	request.open('GET', 'http://api.giphy.com/v1/gifs/' + pandaUrl + '?api_key=dc6zaTOxFJmzC', true);

	request.onload = function() {
		if (request.status >= 200 && request.status < 400){
			data = JSON.parse(request.responseText).data.images.downsized.url;
			console.log(data);
			document.getElementsByClassName("gif")[0].innerHTML = '<img src = "'+data+'"  title="Panda GIF via Giphy">';
			document.getElementsByClassName("spinner")[0].style.display = "none";
		} else {
			document.getElementsByClassName("error")[0].style.display = "inline";
			document.getElementsByClassName("spinner")[0].style.display = "none";
			console.log('reached giphy, but API returned an error');
		}
	};

	request.onerror = function() {
		document.getElementsByClassName("error")[0].style.display = "inline";
		document.getElementsByClassName("spinner")[0].style.display = "none";
		console.log('connection error');
	};

	request.send();
});
